export const GET_ALL_HABITS = 'GET_ALL_HABITS'
export const CREATE_HABIT = 'CREATE_HABIT'
export const UPDATE_HABIT = 'UPDATE_HABIT'
export const DELETE_HABIT = 'DELETE_HABIT'

export const GET_HABITS_CHECK = 'GET_HABITS_CHECK'
export const UPDATE_HABITS_CHECK = 'UPDATE_HABITS_CHECK'
